version: '3.4'

services:
  ip-domain:
    build:
      context: ./IP-Domain
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - "3000:80"
  ip-domain-api:
    image: ${DOCKER_REGISTRY-}ipdomainapi
    build:
      context: .
      dockerfile: IP-Domain-API/Dockerfile
    expose:
      - "80"
    ports:
      - "5101:80"